version: '2'

networks:
  prototype-network:
    driver: bridge

services:
  prototype-cassandra:
    container_name: prototype-cassandra
    image: "cassandra"
    networks:
      - prototype-network
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1

volumes:
  cassandra-data: